name: book
channels:
  - anaconda
  - conda-forge
dependencies:
  - accessible-pygments=0.0.4
  - alabaster=0.7.13
  - anyio=4.0.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - blas=1.0
  - bleach=6.0.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - chardet=5.2.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - cookiecutter=2.3.0
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.7.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.11.0
  - giflib=5.2.1
  - greenlet=2.0.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - intel-openmp=2021.4.0
  - ipdb=0.13.13
  - ipykernel=6.25.2
  - ipython=8.3.0
  - ipywidgets=8.1.0
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.0
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.0
  - jupyter-book=0.15.1
  - jupyter-cache=0.6.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.5
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=3.0.8
  - kiwisolver=1.4.2
  - latexcodec=2.0.1
  - lcms2=2.12
  - libcxx=16.0.6
  - libffi=3.4.2
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - mistune=3.0.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - myst-nb=0.17.2
  - myst-parser=0.18.1
  - nbclient=0.7.4
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook-shim=0.2.3
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=3.1.2
  - overrides=7.4.0
  - packaging=23.1
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybtex=0.24.0
  - pybtex-docutils=1.0.3
  - pycparser=2.21
  - pydata-sphinx-theme=0.13.3
  - pygments=2.16.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-slugify=8.0.1
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.5.1
  - rpds-py=0.10.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.2
  - setuptools=68.1.2
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinx-book-theme=1.0.1
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.3.0
  - sphinx-external-toc=0.3.1
  - sphinx-jupyterbook-latex=0.5.2
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.2.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-bibtex=2.5.0
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - sqlalchemy=2.0.20
  - stack_data=0.6.2
  - tabulate=0.9.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - uri-template=1.3.0
  - urllib3=2.0.4
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.2
  - wheel=0.41.2
  - widgetsnbextension=4.0.8
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
